vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /data
           upload_destination: '%kernel.project_dir%/public/data'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
